# Generated by Django 4.2.3 on 2024-03-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='No title', max_length=200),
        ),
    ]
