# Generated by Django 4.2.3 on 2024-03-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
